name: Usando secretos
run-name: ¡Estoy aprendiendo a usar el varibale secretas!
on:
  push
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-varribales:
    env:
      SALUDO: Hola
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA y usando variables de entorno ${{vars.NAME_REAL_2}}"
        env:
            NOMBRE: Kike2
  saludo-secreto:
      runs-on: ubuntu-latest
      steps:
        - name: Saludo Secreto
          run: echo "$SALUDO, $NOMBRE. Tu contraseña es ${{secrets.CONTRASENA}}"
